### ISSUE TITLE
Too much default values ?

### ISSUE THREAD

**Issue by astik** [amarao/ansible-flyway#1]
In ansible-flyway/defaults/main.yml, you're setting variable like flyway_driver.
But in flyway conf, this is a value that can be autodetect :

From /opt/flyway/flyway-3.2/conf/flyway.conf :

```
# Fully qualified classname of the jdbc driver (autodetected by default based on flyway.url)
# flyway.driver=
```

It may be better to not push too much default variable as they need to be override explicitly then.

**Comment by amarao** [comment]
Yes, you're right.

Thanks!
