### ISSUE TITLE
Add link back to galaxy role to help people use role

### ISSUE THREAD

**Issue by smehan** [amarao/ansible-flyway#14]
To help people benefit from your work, and hopefully help improve the overall role, add https://galaxy.ansible.com/george.shuklin/flyway/ to the title:website of your github repo. Then they can find the role in github and click back to galaxy! See one of my [roles](https://github.com/smehan/ansible-role-compile-python3) if this doesn't make sense.

**Comment by amarao** [comment]
Oh, sorry, I've missed this issue. Bad me. Fixed.
