### ISSUE TITLE
Unpack Flyway

### ISSUE THREAD

**Issue by jonmelia** [amarao/ansible-flyway#19]
Having a problem with the Unpack Flyway element

"changed": false, "msg": "dest '/opt/flyway creates=/opt/flyway/flyway-5.0.1/flyway' must be an existing dir"

This was working fine until I tested today...

**Comment by jonmelia** [comment]
There seems to be an issue with this since it was changed..
- name: Unpack flyway
  unarchive:
    copy: no
    src: '{{ flyway_root }}/flyway-commandline-{{ flyway_version }}.tar.gz'
    dest: '{{ flyway_root }} creates={{ flyway_binary }}'
  when: flyway_status.stat.mode|default(0) != "0755"


I think this should be..
- name: Unpack flyway
  unarchive:
    copy: no
    src: '{{ flyway_root }}/flyway-commandline-{{ flyway_version }}.tar.gz'
    dest: '{{ flyway_root }}' 
    creates: '{{ flyway_binary }}'
  when: flyway_status.stat.mode|default(0) != "0755"

**Comment by amarao** [comment]
Absolutely. I've just integrated role update into our project and my integration test had failed.

I feel ashamed by lack of tests in this role. I'll try to add them (uh... molecule, I tried it once and it was too much for me).

Anyway, I fixed that and my integration test was successful.

Thanks for report.
