### ISSUE TITLE
flyway_validate_ssl_cert: false  var not being passed

### ISSUE THREAD

**Issue by jonmelia** [amarao/ansible-flyway#20]
I have included some vars below in the config of our flyway role based on your role...  However since the changes it will not accept the flyway_validate_ssl_cert: false   var.  This seems to be ignored during deployment

Ansible deployment still shows  "validate_certs": true

I've included my config below to try and understand why this is happening.  I should be able to set the flyway_validate_ssl_cert to false below and it takes precedence over your role, but it seems to be ignoring it.
---
- name: Install flyway
  include_role:
    name: "amarao.ansible-flyway"
  vars:
    - flyway_config:
        database:
          dbms: "{{ db_dbms }}"
          user: "{{ db_username }}"
          host: "{{ db_host }}"
          port: "{{ db_port }}"
          name: "{{ db_name }}?ssl=true"
        schemas: "{{ db_schema }}"
    - flyway_download_url: "https://artifactory.mydomain/maven/maven2/org/flywaydb/flyway-commandline/%s/flyway-commandline-%s.tar.gz"
    - flyway_validate_ssl_cert: false

**Comment by jonmelia** [comment]
I suspect the "omit" is over-riding the settings and ignoring the validate_certs line

**Comment by jonmelia** [comment]
Closing issue typo in code

**Comment by amarao** [comment]
Just in case, you use '-' in `vars` incorrectly. '-' (Dash sign) is a way to encode a list element. When you write: 
```
vars:
    - flyway_config:

```
You are saying that vars contains a list (with dicts as it's elements). For a proper Ansible configuration it should be a dict:

```
vars:
  flyway_config: ...
  flyway_validate_ssl_cert: false
  ...
```

**Comment by jonmelia** [comment]
Thanks for pointing that out, I was copying and pasting 👍
