### ISSUE TITLE
Updating flyway after version update or configuration change

### ISSUE THREAD

**Issue by astik** [amarao/ansible-flyway#3]
For now, once flyway is installed, every task will be skipped when the playbook is run again. This is done because of the check on the symlink /usr/bin/flyway only.

This is not handy when updating flyway version (with the flyway_version variable) or changing the flyway config.
- if the version change, the new flyway has to be installed.
- if the settings change, configuration file needs to be installed

Here is a modified version :

```

---
- name: Check if flyway is already installed
  stat: path={{ flyway_root }}/flyway-{{flyway_version}} follow=yes
  register: flyway_status

- name: debug
  debug: msg="{{flyway_status.stat.mode|default(0)}}"
  when: flyway_status.stat.mode|default(0) != "0755"

- name: Creating directory for flyway
  file: path={{flyway_root}} state=directory
  when: flyway_status.stat.mode|default(0) != "0755"

- name: Downloading flyway
  get_url: url={{flyway_real_url}} dest={{flyway_root}}
  when: flyway_status.stat.mode|default(0) != "0755"

- name: Unpacking flyway
  unarchive: copy=no src={{flyway_root}}/flyway-commandline-{{flyway_version}}.tar.gz dest={{flyway_root}} creates={{flyway_binary}}
  when: flyway_status.stat.mode|default(0) != "0755"

- name: removing downloaded copy
  file: path={{flyway_root}}/flyway-commandline-{{flyway_version}}.tar.gz state=absent
  when: flyway_status.stat.mode|default(0) != "0755"

- name: creating synmink in /usr/bin
  file: src={{flyway_binary}} dest=/usr/bin/flyway state=link

- name: fixing permissions to binary
  file: path={{flyway_binary}} mode=755 state=file

- name: Configuring flyway.properties
  template: src=flyway.properties.j2 dest={{flyway_root}}/flyway-{{flyway_version}}/conf/flyway.properties
```

The first problem is managed by checking the target of the symlink directly. This target has the version in its path. The when condition is removing on the symlink creation.

The second problem is fixed by removing the when condition on the 2 last tasks.

As Ansible execution is idempotent, if configuration files doesn't need to be change they are left as-is.

**Comment by amarao** [comment]
Yes, you right.

Fixing now. 

Thanks.
