### ISSUE TITLE
The configuration file should be named flyway.conf rather than flyway.properties.

### ISSUE THREAD

**Issue by yeroc** [amarao/ansible-flyway#8]
By default flyway looks for flyway.conf rather than flyway.properties so it seems odd that the templated filename is flyway.properties.  Is there some reason for this?

**Comment by amarao** [comment]
Older version had used  flyway.properties (you can see it traces in the help message: configFile                   : Config file to use (default: conf/flyway.properties)).

I'll fix it now, together with  version bump in defaults.

**Comment by yeroc** [comment]
Thanks a lot.  Sorry, I just started using Flyway so wasn't aware of the historical use of the other name.  Is it worth putting a conditional in there based on the Flyway version?
